import { useEffect, useState } from 'react'
import './App.css'

type Quality = { sourceCoverage: string; freshness: string; confidenceContext: string; missingContext: string[]; uncertainty: string[]; limitations: string[]; stale: boolean; conflicting: boolean }
type Context = { period?: string; areaDomainId?: string; serviceId?: string; riskFindingId?: string; comparisonContext?: string }
type Area = { areaDomainId: string; name: string; attentionState: string }
type Service = { serviceId: string; name: string; areaDomainId: string; conditionContext: string }
type Risk = { riskFindingId: string; serviceId: string; condition: string; explanation: string; evidenceBasis: string }
type Evidence = { evidenceId: string; supportedClaim: string; sourceReferenceIds: string[]; observedAt: string }
type Commitment = { commitmentId: string; declaration: string; statusContext: string }
type Action = { actionId: string; commitmentId: string; action: string; executionStatusContext: string }
type Outcome = { verificationId: string; actionId: string; outcome: string; evidenceIds: string[] }
type GraphNode = { canonicalType: string; canonicalId: string }
type GraphRelation = { source: GraphNode; predicate: string; target: GraphNode; evidenceIds: string[]; sourceReferenceIds: string[] }
type GraphView = { graph: { nodes: GraphNode[]; relationships: GraphRelation[]; truncated: boolean; freshness: string }; state: string }
type Overview = { context: Context; areas: Area[]; services: Service[]; attentionFindings: Risk[]; quality: Quality }
type Detail = { context: Context; service?: Service; riskFinding?: Risk; riskFindings: Risk[]; evidence: Evidence[]; commitments: Commitment[]; improvementActions: Action[]; outcomeVerifications: Outcome[]; quality: Quality }

async function read<T>(path: string): Promise<T> { const response = await fetch(path); if (!response.ok) throw new Error(`Experience request failed (${response.status})`); return response.json() as Promise<T> }
function QualityPanel({ quality }: { quality: Quality }) { return <aside className="quality" aria-label="Data quality and limits"><strong>Evidence and limits</strong><span>Coverage: {quality.sourceCoverage}</span><span>Freshness: {quality.freshness}</span><span>Confidence: {quality.confidenceContext}</span>{quality.uncertainty.map((item) => <span key={item}>Uncertainty: {item}</span>)}{quality.missingContext.map((item) => <span key={item}>Missing context: {item}</span>)}{quality.limitations.map((item) => <span key={item}>Limit: {item}</span>)}</aside> }
function ActionOutcomePanel({ detail }: { detail: Detail }) { return <section className="action-outcome"><h2>Action → Outcome</h2><p>Period: {detail.context.period ?? 'not specified'} · Area/Domain: {detail.context.areaDomainId ?? detail.service?.areaDomainId ?? 'not specified'} · Service: {detail.context.serviceId ?? detail.service?.serviceId ?? 'not specified'} · RiskFinding: {detail.context.riskFindingId ?? detail.riskFinding?.riskFindingId ?? 'not specified'}</p>{detail.commitments.length === 0 && <p>No Commitment is present in this projection.</p>}{detail.commitments.map((commitment) => <article key={commitment.commitmentId}><span>Commitment · {commitment.statusContext}</span><h3>{commitment.declaration}</h3>{detail.improvementActions.filter((action) => action.commitmentId === commitment.commitmentId).map((action) => <div className="action" key={action.actionId}><strong>ImprovementAction · {action.executionStatusContext}</strong><p>{action.action}</p>{detail.outcomeVerifications.filter((outcome) => outcome.actionId === action.actionId).map((outcome) => <div className="outcome" key={outcome.verificationId}><strong>OutcomeVerification · {outcome.outcome}</strong><p>{outcome.evidenceIds.length ? `Evidence: ${outcome.evidenceIds.join(', ')}` : 'Insufficient Evidence; outcome is not yet verifiable.'}</p></div>)}{detail.outcomeVerifications.every((outcome) => outcome.actionId !== action.actionId) && <p>OutcomeVerification is not available; execution is not outcome proof.</p>}</div>)}</article>)}</section> }
function GraphPanel({ graph }: { graph?: GraphView }) { if (!graph) return null; return <section className="graph-panel"><h2>Bounded graph context</h2><p>State: {graph.state} · Freshness: {graph.graph.freshness}</p>{graph.graph.nodes.length <= 1 ? <p>Graph context is partial or unavailable; no additional relationship is inferred.</p> : <ul>{graph.graph.relationships.map((relation, index) => <li key={`${relation.predicate}-${index}`}>{relation.source.canonicalType} <strong>--{relation.predicate}--&gt;</strong> {relation.target.canonicalType}</li>)}</ul>}{graph.graph.truncated && <p>Further expansion is bounded.</p>}</section> }
function App() {
  const [overview, setOverview] = useState<Overview>(); const [detail, setDetail] = useState<Detail>(); const [graph, setGraph] = useState<GraphView>(); const [error, setError] = useState<string>()
  useEffect(() => { void read<Overview>('/api/experience/overview?period=local-dataset-v1').then(setOverview).catch((reason: Error) => setError(reason.message)) }, [])
  const selectService = (id: string) => { void read<Detail>(`/api/experience/services/${id}?period=local-dataset-v1`).then(setDetail).catch((reason: Error) => setError(reason.message)); void read<GraphView>(`/api/experience/graph?period=local-dataset-v1&serviceId=${id}&maxNodes=12&maxRelationships=16`).then(setGraph).catch(() => setGraph(undefined)) }
  const selectRisk = (id: string) => { void read<Detail>(`/api/experience/risks/${id}?period=local-dataset-v1&serviceId=${detail?.service?.serviceId ?? ''}`).then(setDetail).catch((reason: Error) => setError(reason.message)); void read<GraphView>(`/api/experience/graph?period=local-dataset-v1&serviceId=${detail?.service?.serviceId ?? ''}&riskFindingId=${id}&maxNodes=12&maxRelationships=16`).then(setGraph).catch(() => setGraph(undefined)) }
  if (error) return <main className="shell"><GraphPanel graph={graph} /><h1>Experience data is unavailable.</h1><p>{error}</p></main>
  if (!overview) return <main className="shell"><h1>Loading operational context…</h1></main>
  return <main className="shell"><header><p className="eyebrow">VECTOR · evidence-first investigation</p><h1>Technology overview</h1><p className="lede">Attention → context → explanation → evidence</p></header><section><h2>Attention</h2><div className="cards">{overview.areas.map((area) => <article key={area.areaDomainId}><span className="state">{area.attentionState}</span><h3>{area.name}</h3></article>)}</div></section><section><h2>Context</h2><div className="cards">{overview.services.map((service) => <button className="card-button" key={service.serviceId} onClick={() => selectService(service.serviceId)}><span>Service</span><h3>{service.name}</h3><p>{service.conditionContext}</p></button>)}</div></section>{detail?.service && <section><h2>Explanation</h2><article className="panel"><h3>{detail.service.name}</h3>{detail.riskFindings.map((risk) => <button className="risk" key={risk.riskFindingId} onClick={() => selectRisk(risk.riskFindingId)}><strong>{risk.condition}</strong><span>{risk.explanation}</span></button>)}<ActionOutcomePanel detail={detail} /><QualityPanel quality={detail.quality} /></article></section>}{detail?.riskFinding && <section><h2>Evidence</h2><article className="panel"><h3>{detail.riskFinding.condition}</h3><p>{detail.riskFinding.explanation}</p><div className="evidence-list">{detail.evidence.map((item) => <div key={item.evidenceId}><strong>{item.supportedClaim}</strong><span>Source: {item.sourceReferenceIds.join(', ')}</span><small>Observed: {item.observedAt}</small></div>)}</div><ActionOutcomePanel detail={detail} /><QualityPanel quality={detail.quality} /></article></section>}{!detail && <QualityPanel quality={overview.quality} />}</main>
}
export default App
