import { useEffect, useState } from 'react'

type Area = { areaDomainId: string; name: string; attentionState: string }
type Service = { serviceId: string; name: string; areaDomainId: string; conditionContext: string }
type Risk = { riskFindingId: string; serviceId: string; condition: string; explanation: string }
type Overview = { areas: Area[]; services: Service[]; attentionFindings: Risk[] }
const pretty = (value: string) => value.replace(/^(area-|service-)/, '').replace(/[-:]/g, ' ').replace(/\b\w/g, (letter) => letter.toUpperCase())

export default function AreaOverlay() {
  const [data, setData] = useState<Overview>(); const [path, setPath] = useState(window.location.pathname)
  useEffect(() => { const onPopState = () => setPath(window.location.pathname); window.addEventListener('popstate', onPopState); return () => window.removeEventListener('popstate', onPopState) }, [])
  useEffect(() => { if (path !== '/areas') return; void fetch('/api/experience/overview?period=local-dataset-v1').then((response) => response.json()).then(setData) }, [path])
  if (path !== '/areas' || !data) return null
  const areaId = new URLSearchParams(window.location.search).get('areaDomainId'); const area = data.areas.find((item) => item.areaDomainId === areaId) ?? data.areas[0]; const services = data.services.filter((item) => item.areaDomainId === area?.areaDomainId); const serviceIds = new Set(services.map((item) => item.serviceId)); const findings = data.attentionFindings.filter((item) => serviceIds.has(item.serviceId))
  return <section className="area-overlay"><div className="page"><div className="breadcrumb"><span>Panorama Ejecutivo</span><span>/</span><span>Area Intelligence</span></div><header className="page-header"><div><p className="eyebrow">Management experience</p><h1>Area Intelligence</h1><p className="lede">What is happening in this Area / Domain and where should I go deeper?</p></div></header><section className="area-hero"><div><div className="section-kicker">Selected Area / Domain</div><h2>{area?.name ?? 'No Area selected'}</h2><p>Retained context for services, reliability conditions, and evidence-backed attention.</p></div><span className="status status-warning">{area?.attentionState ?? 'UNAVAILABLE'}</span></section><div className="area-summary"><div><span>Services in context</span><strong>{services.length}</strong><small>Available in this period</small></div><div><span>Attention findings</span><strong>{findings.length}</strong><small>Evidence-backed where available</small></div><div><span>Decision focus</span><strong>Area</strong><small>Area → Service → Risk</small></div></div><div className="area-content-grid"><section className="panel"><div className="section-kicker">Attention drivers</div><h2>What needs attention?</h2>{findings.length ? findings.map((finding) => <article className="driver-row" key={finding.riskFindingId}><span className="signal-ring" /><div><strong>{finding.condition}</strong><p>{finding.explanation}</p><small>Service · {pretty(finding.serviceId)}</small></div></article>) : <p className="empty-state">No additional findings are available for this Area / Domain.</p>}</section><section className="panel"><div className="section-kicker">Service context</div><h2>Services requiring attention</h2>{services.map((service) => <article className="service-context-row" key={service.serviceId}><span className="service-status" /><div><strong>{service.name}</strong><p>{service.conditionContext}</p></div><span className="card-link">Open →</span></article>)}</section></div></div></section>
}
