import { useEffect, useState } from 'react'

type Risk = { riskFindingId: string; serviceId: string; condition: string; explanation: string }
type Evidence = { evidenceId: string; supportedClaim: string; sourceReferenceIds: string[]; observedAt: string }
type Graph = { graph: { relationships: { source: { canonicalId: string }; predicate: string; target: { canonicalId: string } }[]; freshness: string; truncated: boolean }; state: string }
type Data = { context: { areaDomainId?: string }; riskFinding?: Risk; evidence: Evidence[] }

const pretty = (value: string) => value.replace(/^(area-|service-|evidence-|risk-finding:)/, '').replace(/[-:]/g, ' ').replace(/\b\w/g, (letter) => letter.toUpperCase())
const load = async <T,>(url: string) => { const response = await fetch(url); if (!response.ok) throw new Error('Risk context unavailable'); return response.json() as Promise<T> }

export default function RiskOverlay() {
  const [data, setData] = useState<Data>(); const [graph, setGraph] = useState<Graph>(); const [path, setPath] = useState(window.location.pathname)
  useEffect(() => { const onPopState = () => setPath(window.location.pathname); window.addEventListener('popstate', onPopState); return () => window.removeEventListener('popstate', onPopState) }, [])
  useEffect(() => { if (!path.startsWith('/risks/')) return; const riskId = decodeURIComponent(path.split('/')[2] ?? ''); const params = new URLSearchParams(window.location.search); const serviceId = params.get('serviceId') ?? 'service-payments'; void load<Data>(`/api/experience/risks/${encodeURIComponent(riskId)}?period=local-dataset-v1&serviceId=${encodeURIComponent(serviceId)}`).then(setData); void load<Graph>(`/api/experience/graph?period=local-dataset-v1&serviceId=${encodeURIComponent(serviceId)}&riskFindingId=${encodeURIComponent(riskId)}&maxNodes=12&maxRelationships=16`).then(setGraph) }, [path])
  if (!path.startsWith('/risks/') || !data?.riskFinding) return null
  const risk = data.riskFinding
  return <section className="risk-overlay"><div className="page"><div className="breadcrumb"><span>Panorama Ejecutivo</span><span>/</span><span>{pretty(data.context.areaDomainId ?? 'area-platform')}</span><span>/</span><span>Risk Investigation</span></div><header className="page-header"><div><p className="eyebrow">SRE / Risk Investigation</p><h1>Risk Investigation</h1><p className="lede">Trace the condition through bounded evidence, graph context, action, and outcome.</p></div></header><div className="context-strip"><span>Area / Domain <b>{pretty(data.context.areaDomainId ?? 'area-platform')}</b></span><span>Service <b>{pretty(risk.serviceId)}</b></span><span>RiskFinding <b>{risk.condition}</b></span></div><div className="investigation-grid"><section className="panel"><div className="section-kicker">Explanation</div><h2>{risk.condition}</h2><p className="lead-copy">{risk.explanation}</p><div className="evidence-list"><div className="section-kicker">Evidence timeline</div>{data.evidence.map((item) => <article className="evidence-card" key={item.evidenceId}><div className="timeline-dot" /><div><div className="row-top"><strong>{item.supportedClaim}</strong><span className="muted">{item.observedAt}</span></div><p>Observed Evidence · {item.sourceReferenceIds.map(pretty).join(', ')}</p></div></article>)}</div></section><section className="panel graph-panel"><div className="panel-heading"><div><div className="section-kicker">Investigation workspace</div><h2>Bounded graph context</h2></div><span className="status status-neutral">{graph?.state ?? 'loading'}</span></div><p className="muted">Freshness · {graph?.graph.freshness ?? 'pending'}</p><div className="graph-list">{graph?.graph.relationships.map((relation, index) => <div className="graph-edge" key={`${relation.predicate}-${index}`}><span>{pretty(relation.source.canonicalId)}</span><b>{relation.predicate.replaceAll('_', ' ')}</b><span>{pretty(relation.target.canonicalId)}</span></div>)}</div>{graph?.graph.truncated && <p className="quality-note">Further expansion is bounded.</p>}</section></div><aside className="quality-panel"><div className="section-kicker">Data quality</div><h3>Evidence and limits</h3><p className="quality-note">Source authority and provenance remain visible. Missing or uncertain context is not inferred.</p><p className="noncausal">J02 Change/Deployment context is temporal/contextual; Correlation != Causation.</p></aside></div></section>
}
