import { useEffect, useState } from 'react'

type Risk = { riskFindingId: string; serviceId: string; condition: string; explanation: string }
type Evidence = { evidenceId: string; supportedClaim: string; sourceReferenceIds: string[]; observedAt: string }
type Commitment = { commitmentId: string; declaration: string; statusContext: string }
type Action = { actionId: string; commitmentId: string; action: string; executionStatusContext: string }
type Outcome = { verificationId: string; actionId: string; outcome: string; evidenceIds: string[] }
type Graph = { graph: { relationships: { source: { canonicalId: string }; predicate: string; target: { canonicalId: string } }[]; freshness: string; truncated: boolean }; state: string }
type Data = { context: { areaDomainId?: string }; riskFinding?: Risk; evidence: Evidence[]; commitments: Commitment[]; improvementActions: Action[]; outcomeVerifications: Outcome[] }
type Overview = { attentionFindings: Risk[] }

const pretty = (value: string) => value.replace(/^(area-|service-|evidence-|risk-finding:)/, '').replace(/[-:]/g, ' ').replace(/\b\w/g, (letter) => letter.toUpperCase())
const load = async <T,>(url: string) => { const response = await fetch(url); if (!response.ok) throw new Error('Risk context unavailable'); return response.json() as Promise<T> }

function ActionOutcome({ data }: { data: Data }) { return <section className="panel action-outcome"><div className="section-kicker">Decision continuity</div><h2>Action <span>→</span> Outcome</h2><p className="muted">Execution is tracked separately from structural outcome verification.</p>{data.commitments.map((commitment) => <article className="commitment-row" key={commitment.commitmentId}><div className="row-top"><span className="label">Commitment</span><span className="status status-success">{commitment.statusContext}</span></div><h3>{commitment.declaration}</h3>{data.improvementActions.filter((action) => action.commitmentId === commitment.commitmentId).map((action) => <div className="action-row" key={action.actionId}><div className="row-top"><span className="label">ImprovementAction</span><span className="status status-success">{action.executionStatusContext}</span></div><p>{action.action}</p>{data.outcomeVerifications.filter((outcome) => outcome.actionId === action.actionId).map((outcome) => <div className="outcome-row" key={outcome.verificationId}><div className="row-top"><span className="label">OutcomeVerification</span><span className="status status-warning">{outcome.outcome}</span></div><p>{outcome.evidenceIds.length ? `Evidence: ${outcome.evidenceIds.map(pretty).join(', ')}` : 'Insufficient Evidence; outcome is not yet verifiable.'}</p></div>)}</div>)}</article>)}</section> }

export default function RiskOverlay() {
  const [data, setData] = useState<Data>(); const [graph, setGraph] = useState<Graph>(); const [path, setPath] = useState(window.location.pathname)
  useEffect(() => { const onPopState = () => setPath(window.location.pathname); window.addEventListener('popstate', onPopState); return () => window.removeEventListener('popstate', onPopState) }, [])
  useEffect(() => { if (path !== '/risks' && !path.startsWith('/risks/')) return; const resolve = async () => { const params = new URLSearchParams(window.location.search); let riskId = decodeURIComponent(path.split('/')[2] ?? '') || params.get('riskFindingId') || ''; let serviceId = params.get('serviceId') || ''; if (!riskId) { const overview = await load<Overview>('/api/experience/overview?period=local-dataset-v1'); const first = overview.attentionFindings[0]; riskId = first?.riskFindingId ?? ''; serviceId = serviceId || first?.serviceId || '' } if (!riskId) return; const riskUrl = `/api/experience/risks/${encodeURIComponent(riskId)}?period=local-dataset-v1${serviceId ? `&serviceId=${encodeURIComponent(serviceId)}` : ''}`; const [riskData, graphData] = await Promise.all([load<Data>(riskUrl), load<Graph>(`/api/experience/graph?period=local-dataset-v1&serviceId=${encodeURIComponent(serviceId)}&riskFindingId=${encodeURIComponent(riskId)}&maxNodes=12&maxRelationships=16`)]); setData(riskData); setGraph(graphData) }; void resolve() }, [path])
  if ((path !== '/risks' && !path.startsWith('/risks/')) || !data?.riskFinding) return null
  const risk = data.riskFinding
  return <section className="risk-overlay"><div className="page"><div className="breadcrumb"><span>Panorama Ejecutivo</span><span>/</span><span>{pretty(data.context.areaDomainId ?? 'area-platform')}</span><span>/</span><span>Risk Investigation</span></div><header className="page-header"><div><p className="eyebrow">SRE / Risk Investigation</p><h1>Risk Investigation</h1><p className="lede">Trace the condition through bounded evidence, graph context, action, and outcome.</p></div></header><div className="context-strip"><span>Area / Domain <b>{pretty(data.context.areaDomainId ?? 'area-platform')}</b></span><span>Service <b>{pretty(risk.serviceId)}</b></span><span>RiskFinding <b>{risk.condition}</b></span></div><div className="investigation-grid"><section className="panel"><div className="section-kicker">Explanation</div><h2>{risk.condition}</h2><p className="lead-copy">{risk.explanation}</p><div className="evidence-list"><div className="section-kicker">Evidence timeline</div>{data.evidence.map((item) => <article className="evidence-card" key={item.evidenceId}><div className="timeline-dot" /><div><div className="row-top"><strong>{item.supportedClaim}</strong><span className="muted">{item.observedAt}</span></div><p>Observed Evidence · {item.sourceReferenceIds.map(pretty).join(', ')}</p></div></article>)}</div></section><section className="panel graph-panel"><div className="panel-heading"><div><div className="section-kicker">Investigation workspace</div><h2>Bounded graph context</h2></div><span className="status status-neutral">{graph?.state ?? 'loading'}</span></div><p className="muted">Freshness · {graph?.graph.freshness ?? 'pending'}</p><div className="graph-list">{graph?.graph.relationships.map((relation, index) => <div className="graph-edge" key={`${relation.predicate}-${index}`}><span>{pretty(relation.source.canonicalId)}</span><b>{relation.predicate.replaceAll('_', ' ')}</b><span>{pretty(relation.target.canonicalId)}</span></div>)}</div>{graph?.graph.truncated && <p className="quality-note">Further expansion is bounded.</p>}</section></div><aside className="quality-panel"><div className="section-kicker">Data quality</div><h3>Evidence and limits</h3><p className="quality-note">Source authority and provenance remain visible. Missing or uncertain context is not inferred.</p><p className="noncausal">J02 Change/Deployment context is temporal/contextual; Correlation != Causation.</p></aside><ActionOutcome data={data} /></div></section>
}
